SELECT DISTINCT CITY
FROM STATION
WHERE (NOT CITY LIKE 'A%'
AND NOT CITY LIKE 'E%'
AND NOT CITY LIKE 'I%'
AND NOT CITY LIKE 'O%'
AND NOT CITY LIKE 'U%')
OR
(NOT CITY LIKE '%a'
AND NOT CITY LIKE '%e'
AND NOT CITY LIKE '%i'
AND NOT CITY LIKE '%o'
AND NOT CITY LIKE '%u');
